/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Arigaia Sekuin (https://sketchfab.com/arigaia.sekuin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abstract-ball-ffafe62053a745b8b2c8182e59239e79
Title: Abstract Ball
*/
"use client";
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

const BookModel = React.memo(function BookModel(props) {
  const { nodes, materials } = useGLTF('/models/about-transformed.glb')

  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.012;
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={[0.7, 0.7, 0.7]}
      rotation={[0.4, -1, 0]}
      position={[0, 1.0, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere002_0.geometry}
        material={materials['ballz2.002']}
        rotation={[-1.49, 1.315, 0.904]}
        scale={1.251}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere003_0.geometry}
        material={materials['Lightballz.002']}
        rotation={[-1.49, 1.315, 0.904]}
        scale={1.251}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_0.geometry}
        material={materials['Wireframy.002']}
        rotation={[2.161, 0.868, -3.138]}
        scale={1.251}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003_0.geometry}
        material={materials['Ballz.002']}
        rotation={[-2.139, 0.997, 1.709]}
        scale={1.251}
      />
    </group>
  )
})

export default BookModel;
useGLTF.preload('/models/about-transformed.glb')